# Generated by Django 3.2.7 on 2021-09-16 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 10, 54, 7, 31164, tzinfo=utc), verbose_name='投稿日時'),
        ),
    ]
