# Generated by Django 3.2.7 on 2021-09-16 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_alter_voice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
    ]
